name: Testes

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Instalar dependências
        run: npm ci

      - name: Executar testes
        run: npm test

      - name: Publicar relatório
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: relatorio-testes
          path: reports/